# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(to='images.Categories'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(blank=True, upload_to='base-images/'),
        ),
    ]
